# Generated by Django 2.2.6 on 2020-11-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201103_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cod',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
