# Generated by Django 2.2.6 on 2020-11-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201103_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ape',
            field=models.CharField(max_length=200, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='customer',
            name='dni',
            field=models.CharField(max_length=7, null=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=200, null=True, verbose_name='Celular'),
        ),
    ]
