# Generated by Django 2.2.6 on 2020-11-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201103_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ape',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
